services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - internal-docker

networks:
  internal-docker:
    external: true
